import { Theme } from './theme.types';

export const theme: Theme = {
  color: {
    component: {
      bottomMenuBackground: '#010101',
      bottomMenuText: '#FFFFFF',
      ordinalSelectedBorder: '#fcd34d',
      ordinalTypeJson: '#fbbf24',
      ordinalTypePlainText: '#fbbf24',
      ordinalTypeUnsupported: '#FFFFFF',
      pageLoaderSpinner: '#fcd34d',
      pageLoaderSpinnerBorder: '#FFFFFF50',
      pageLoaderText: '#FFFFFF',
      primaryButtonLeftGradient: '#fde047',
      primaryButtonRightGradient: '#f59e0b',
      primaryButtonText: '#010101',
      progressBar: '#fbbf24',
      progressBarTrack: '#F5F5F5',
      queueBannerSynced: '#fbbf24',
      queueBannerSyncedText: '#000000',
      queueBannerSyncing: '#F79009',
      queueBannerSyncingText: '#000000',
      secondaryOutlineButtonGradientLeft: '#fde047',
      secondaryOutlineButtonGradientRight: '#f59e0b',
      secondaryOutlineButtonText: '#010101',
      snackbarError: '#FF4646',
      snackbarErrorText: '#000000',
      snackbarSuccess: '#fbbf24',
      snackbarSuccessText: '#000000',
      snackbarWarning: '#F79009',
      snackbarWarningText: '#000000',
      tabSelectedLeftGradient: '#fde047',
      tabSelectedRightGradient: '#f59e0b',
      tabSelectedText: '#010101',
      tabUnselected: '#17191E',
      tabUnselectedText: '#FFFFFF',
      toggleSwitchOn: '#fbbf24',
      warningButton: '#FF4646',
      warningButtonText: '#FFFFFF',
    },
    global: {
      neutral: '#000000',
      gray: '#98A2B3',
      row: '#17191E',
      walletBackground: '#010101',
      contrast: '#FFFFFF',
    },
  },
  settings: {
    repo: 'https://github.com/bitcoin-apps-suite/bitcoin-wallet',
    services: {
      apps: true,
      bsv20: true,
      locks: true,
      ordinals: true,
      mnee: true,
    },
    walletName: 'Bitcoin',
  },
};
